spring.application.name=UUPokedexSeptiembre2025Client

# Port
server.port = 8081

# Base URL del Service
pokedex.service.base-url=http://localhost:8080

# Para que nuestra vista sea la que se muestre, quitamos por la de defecto
server.error.whitelabel.enabled=false
